name: update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ update ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Check for updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: scripts/update.sh

    - name: Update the repository
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit
      with:
        commit_message: "Update formula"
